//
//  ReportInsightsViewController.swift
//  Dialysis One App
//
//  Created by user@22 on 31/01/26.
//

import UIKit

final class ReportInsightsViewController: UIViewController {

    private let scroll = UIScrollView()
    private let content = UIStackView()

    private let report: BloodReport
    private let allReports: [BloodReport]

    init(report: BloodReport, allReports: [BloodReport]) {
        self.report = report
        self.allReports = allReports
        super.init(nibName: nil, bundle: nil)
    }

    required init?(coder: NSCoder) { fatalError() }

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .systemBackground
        buildUI()
    }

    private func buildUI() {

        scroll.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(scroll)

        NSLayoutConstraint.activate([
            scroll.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            scroll.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            scroll.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            scroll.bottomAnchor.constraint(equalTo: view.bottomAnchor)
        ])

        content.axis = .vertical
        content.spacing = 16
        content.translatesAutoresizingMaskIntoConstraints = false
        scroll.addSubview(content)

        NSLayoutConstraint.activate([
            content.topAnchor.constraint(equalTo: scroll.topAnchor, constant: 20),
            content.leadingAnchor.constraint(equalTo: scroll.leadingAnchor, constant: 16),
            content.trailingAnchor.constraint(equalTo: scroll.trailingAnchor, constant: -16),
            content.bottomAnchor.constraint(equalTo: scroll.bottomAnchor),
            content.widthAnchor.constraint(equalTo: scroll.widthAnchor, constant: -32)
        ])

        // Info card (always on top)
        content.addArrangedSubview(makeInfoCard())

        let insights = InsightEngine.generateInsights(
            from: report,
            previousReports: allReports
        )

        let grouped = Dictionary(grouping: insights, by: { $0.section })

        if let summary = grouped[.summary], let first = summary.first {

            content.addArrangedSubview(makeSectionHeader("Summary"))

            // ✅ Summary back in a card (no title inside)
            let summaryCard = InsightCardView(insight: first)
            content.addArrangedSubview(summaryCard)
        }

        if let vitals = grouped[.vital] {
            content.addArrangedSubview(makeSectionHeader("Vital Insights"))
            vitals.forEach {
                content.addArrangedSubview(InsightCardView(insight: $0))
            }
        }

    }
    
    private func makeSectionHeader(_ title: String) -> UIView {
        let label = UILabel()
        label.text = title
        label.font = .boldSystemFont(ofSize: 20)
        label.textColor = .label
        return label
    }

    private func makeInfoCard() -> UIView {

        let icon = UIImageView(image: UIImage(systemName: "info.circle"))
        icon.tintColor = .secondaryLabel
        icon.translatesAutoresizingMaskIntoConstraints = false

        let label = UILabel()
        label.text =
        """
        Insights are generated by analysing patterns in your uploaded reports.
        They are meant to help you understand trends and are not medical advice.
        """
        label.font = .systemFont(ofSize: 13)
        label.textColor = .secondaryLabel
        label.numberOfLines = 0

        let hStack = UIStackView(arrangedSubviews: [icon, label])
        hStack.axis = .horizontal
        hStack.spacing = 8
        hStack.alignment = .top
        hStack.translatesAutoresizingMaskIntoConstraints = false

        let container = UIView()
        container.backgroundColor = UIColor.systemGray6
        container.layer.cornerRadius = 14

        container.addSubview(hStack)

        NSLayoutConstraint.activate([
            hStack.topAnchor.constraint(equalTo: container.topAnchor, constant: 12),
            hStack.leadingAnchor.constraint(equalTo: container.leadingAnchor, constant: 12),
            hStack.trailingAnchor.constraint(equalTo: container.trailingAnchor, constant: -12),
            hStack.bottomAnchor.constraint(equalTo: container.bottomAnchor, constant: -12),

            icon.widthAnchor.constraint(equalToConstant: 16),
            icon.heightAnchor.constraint(equalToConstant: 16)
        ])

        return container
    }

}
